previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    name: Bezirksregionenprofile
    env: static
    staticPublishPath: dist
    plan: starter
    pullRequestPreviewsEnabled: false # optional
    previewPlan: starter
    buildCommand: npm run build
